// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nodeVars
IntegerVector nodeVars(IntegerVector varnodes, int nrnodes, int p, IntegerVector parents, IntegerVector idcskeep, IntegerVector nodect, int rowoffset, IntegerVector nodevars);
RcppExport SEXP iRF_nodeVars(SEXP varnodesSEXP, SEXP nrnodesSEXP, SEXP pSEXP, SEXP parentsSEXP, SEXP idcskeepSEXP, SEXP nodectSEXP, SEXP rowoffsetSEXP, SEXP nodevarsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type varnodes(varnodesSEXP);
    Rcpp::traits::input_parameter< int >::type nrnodes(nrnodesSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type parents(parentsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type idcskeep(idcskeepSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nodect(nodectSEXP);
    Rcpp::traits::input_parameter< int >::type rowoffset(rowoffsetSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nodevars(nodevarsSEXP);
    rcpp_result_gen = Rcpp::wrap(nodeVars(varnodes, nrnodes, p, parents, idcskeep, nodect, rowoffset, nodevars));
    return rcpp_result_gen;
END_RCPP
}
