# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nodeObs <- function(obsnodes, n, ntree, nrnodes, nodeobs) {
    .Call('iRF_nodeObs', PACKAGE = 'iRF', obsnodes, n, ntree, nrnodes, nodeobs)
}

nodeVars <- function(varnodes, p, ntree, maxnodes, nr, nrnodes, nodevars, idcskeep) {
    .Call('iRF_nodeVars', PACKAGE = 'iRF', varnodes, p, ntree, maxnodes, nr, nrnodes, nodevars, idcskeep)
}

