plotInt2 <- function(x, y, int, 
                     rectangles=NULL,
                     read.forest=NULL, 
                     grid.size=100, 
                     col.pal=c('blue', 'yellow'), 
                     xlab=NULL, ylab=NULL, zlab=NULL,
                     range.color=NULL,
                     z.range=c(0,1),
                     n.cols=100, 
                     grids=NULL, 
                     axes=TRUE,
                     varnames.grp=colnames(x),
                     pred.prob=FALSE, 
                     min.node=10) {
  # Generates surface map of order-2 interaction
  # args:
  #   x: design matrix
  #   y: response vector
  #   int: order-2 signed interaction to plot, formatted as <xi>_<xj>
  #   rectangles: hyprerectangle list as generated by forestHR
  #   read.forest: list output of readForest, required if rectangles is null
  #   grid.size: number of bins to plot surface map over
  #   col.pal: color palette of surface map
  #   xlab, ylab, zlab: axis labels
  #   range.color: range of color values
  #   z.range: range for response axis
  #   n.cols: number of colors in color pal
  #   grids: user generated grid to plot over. If supplied, grid.size is 
  #     ignored
  #   axes: T/F indicating whether axes should be plotted
  #   varnames.group: character vector indicating feature grouping
  #   pred.prob: T/F indicating whether the z axis should indicate predicted
  #     probability from the forest or raw data distribution
  #   min.node: minimum leaf node size to use for grid
  stopifnot(!is.null(rectangles) | !is.null(read.forest))
  if (is.null(varnames.grp)) varnames.grp <- 1:ncol(x)
  
  int <- int2Id(int, varnames.grp, signed=TRUE)
  stopifnot(length(interact) == 2) 
  i1 <- int[1] %% p + p * (int[1] %% p == 0)
  i2 <- int[2] %% p + p * (int[2] %% p == 0)

  if (is.factor(y)) y <- as.numeric(y) - 1
  n <- nrow(x)
  p <- ncol(x)
  
  # generate grid to plot surface over either as raw values or quantiles
  if (is.null(grids)) {
    g1 <- seq(min(x[,i1]), max(x[,i1]), length.out=grid.size)
    g2 <- seq(min(x[,i2]), max(x[,i2]), length.out=grid.size)
    g1n <- round(g1, 2)
    g2n <- round(g2, 2)
  } else {
    g1 <- grids$g1
    g2 <- grids$g2
    g1n <- seq(0, 1, length.out=length(g1))
    g2n <- seq(0, 1, length.out=length(g2))
    grid.size <- length(g1)
  }
 
  # Evaluate responses over grid based on RF hyperrectangles
  if (is.null(rectangles)) rectangles <- forestHR(read.forest, int) 
  grid <- matrix(0, nrow=grid.size, ncol=grid.size)
  removed <- rep(FALSE, nrow(rectangles))
  for (i in 1:nrow(rectangles)) {
    
    rcur <- rectangles[i,]
    wt <- rectangles$size.node[i]
    tt1 <- unlist(rcur$splits)[unlist(rcur$vars) == int[1]]
    tt2 <- unlist(rcur$splits)[unlist(rcur$vars) == int[2]]
    
    # Evalaute which observations/grid elements correspond to current HR
    if (int1 <= p) {
      idcs1 <- g1 < tt1
      x1 <- x[, i1] < tt1
    } else {
      idcs1 <- g1 >= tt1
      x1 <- x[,i1] >= tt1
    }
    
    if (int2 <= p) {
      idcs2 <- g2 < tt2
      x2 <- x[, i2] < tt2
    } else {
      idcs2 <- g2 >= tt2
      x2 <- x[,i2] >= tt2
    }
    

    if (pred.prob) {
      # Evaluate RF predictions for region corresponding to current HR
      yy <- rectangles$prediction[i]
      grid[idcs1, idcs2] <- grid[idcs1, idcs2] + yy * wt
    } else {
      # Evaluate average response value in regions corresponding to HR
     
      # Remove regions containing no observations
      if (!any(x1 & x2)) {
        removed[i] <- TRUE
        next
      }
      
      # Evaluate distribution of responses in region and complement
      yreg <- mean(y[x1 & x2])
      yregc <- mean(y[!x1 | !x2])
      wt <- rectangles$size.node[i]
      
      grid[idcs1, idcs2] <- grid[idcs1, idcs2] +  yreg * wt
      grid[idcs1, idcs2] <- grid[idcs1, idcs2] -  yregc * wt
      grid <- grid + yregc * wt

    }
  }
  
  # rescale surface for node size and generate corresponding color palette
  grid <- grid / sum(rectangles$size.node[!removed])
  
  if (is.null(range.color)) range.color <- range(grid)
  palette <- colorRampPalette(col.pal)
  colors <- palette(n.cols)
  facet.col <- cut(c(range.color, as.vector(grid)), n.cols)[-seq(2)]
  
  # Plot interaction response surface
  persp3d(x=g1n, y=g2n, z=grid, xlab=xlab, ylab=ylab, zlab=zlab, 
          zlim=z.range, col=colors[facet.col], axes=axes)
  
}

facetSurface <- function(int, nf, tree.info, varnames.grp, x, 
                         y, qcut=0.5, xlab, ylab, min.node, plot.dir) {
  # Generates surface plots for first two interacting features by levels 
  # of the remaining features
  # args:
  #   int: interaction to plot
  #   nf: a node feature sparse matrix, as returned from readForest
  #   tree.info: leaf node metadata, as returned by readForest
  #   varnames.group: character vector indicating feature groupings
  #   x: data matrix, possibly containing replicate features
  #   xg:
  
  # evaluate median thresholds for faceting variables
  id.int <- int2Id(int, varnames.grp=varnames.grp, split=TRUE, signed=TRUE)
  id.nf <- apply(nf[,id.int], MAR=1, function(z) all(z != 0))
  qq <- function(x) quantile(x, probs = qcut)
  thresholds <- apply(nf[id.nf, id.int], MAR=2, qq)
  sgn <- intSign(int)
  
  if (length(int) > 2) {
    id.facet <- 3:length(int)
    int.clean <- gsub('[-\\+]', '', int)
    xx <- t(x[,int.clean[id.facet]]) * sgn[id.facet]
    thresholds[id.facet] <- thresholds[id.facet] * sgn[id.facet]
    id <- xx > thresholds[id.facet]
    id <- apply(id, MAR=1, as.numeric)
    id <- apply(id, MAR=1, paste, collapse='_')
  } else {
    int.clean <- gsub('[-\\+]', '', int)
    id <- rep(1, nrow(x))
    id.facet <- 1:2
  }
  
  grids <- quantileGrid(x, 50, interact=int.clean[1:2])
  
  rectangles <- forestHR(tree.info=tree.info, nf=nf, int=int, 
                         varnames.grp=varnames.grp, min.node=min.node)
  
  
  # iterate through each facet and generate surface plot
  for (ii in unique(id)) {
    open3d()
    id.cur <- id == ii
    nn <- sum(id.cur)
    if (nn < 100) {
      print(ii) 
      next
    }
    
    plotInt2(rectangles, interact=int[1:2], x=x[id.cur,], 
             y=as.factor(y[id.cur]), varnames.grp=varnames.grp, 
             min.node=min.node, grids=grids,
             xlab=xlab, ylab=ylab, zlab='P(Y=1)')
    
    if (!is.null(plot.dir)) {
      pp <- paste(int.clean[id.facet], collapse='_')
      sub.dir <- paste0(plot.dir, pp, '-', ii, '_n', nn)
      dir.create(sub.dir, recursive=TRUE)
      rgl.viewpoint(zoom=0.85, theta=0, phi=-75)
      movie3d(spin3d(axis = c(0,0,1), rpm = 10), duration=6,  type="png", 
              dir=sub.dir, convert=FALSE, clean=FALSE)
    }
  }
}



getPathsTree <- function(read.forest, int) {
  # Extract decision paths across all leaf nodes in a given tree.
  # args:
  #   read.forest: list as returned by readForest, including node.feature and
  #     tree.info entries
  #   int: a numeric vector indicating interaciton variables
  
  nf <- read.forest$node.feature
  out <- select(read.forest$tree.info, prediction, node.idx, tree, size.node)
  
  # Filter nodes to active interactions
  id <- Matrix::rowMeans(nf[,int] != 0) == 1
  out <- out[id,]
  nf <- nf[id,]

  # Extract splitting features and thresholds from decision paths
  row <- nf@i + 1
  col <- findInterval(seq(nf@x)-1, nf@p[-1])+1
  thr <- nf@x

  out$vars <- sapply(unique(row), function(r) col[row == r])
  out$splits <- sapply(unique(row), function(r) thr[row == r])
  return(out)
}

forestHyperrectangle <- function(read.forest, int, varnames.grp, min.node=1) {
  # Read hyperrectangles from RF for a specified interactin
  # args:
  #   read.forest: list as returned by readForest, including node.feature and
  #     tree.info entries
  #   varnames.group: character vector indicating feature grouping
  #   int: vector of features for which to generate hyperrectangles
  #   min.node.size: filter all leaf nodes that are not larger than specified 
  #     value for faster processing
  
  int <- str_split(int, '_')[[1]]
  int <- int2Id(int, varnames.grp, signed=TRUE, split=TRUE)

  out <- getPathsTree(read.forest, int) 
  out <- filter(out, size.node > min.node.size)
  
  return(out)
}

quantileGrid <- function(x, grid.size, interact) {
  stopifnot(length(interact) == 2)
  grid.size <- grid.size + 1
  grids <- list()
  grids$g1 <- quantile(x[,interact[1]], probs=seq(0, 1, length.out=grid.size))
  grids$g2 <- quantile(x[,interact[2]], probs=seq(0, 1, length.out=grid.size))
  return(grids)
}
