getPathsTree <- function(tree.info, nf, interact) {
  # Extract decision paths across all leaf nodes in a given tree.
  # args:
  #   tree.info: data frame as returned by readForest
  #   nf: a node feature sparse matrix, as returned by readForest
  #   interact: a numeric vector indicating interaciton variables
  require(data.table)
  require(dplyr)
  
  out <- select(tree.info, prediction, node.idx, tree, size.node)
  out$vars <- apply(nf, MAR=1, function(z) which(z != 0))
  out$splits <- apply(nf, MAR=1, function(z) z[which(z != 0)])
  id <- sapply(out$vars, function(z) all(interact %in% z))
  out <- out[id,]
  
  return(out)
}

forestHyperrectangle <- function(tree.info, nf, x, y, interact, 
                                 varnames.grp=NULL, min.node.size=1) {
  # Read hyperrectangles from RF for a specified interactin
  # args:
  #   tree.info: data frame as returned by readForest
  #   nf: a node feature sparse matrix, as returned by readForest
  #   x: data matrix
  #   y: response vector
  #   varnames.group: character vector indicating feature grouping
  #   interact: vector of features for which to generate hyperrectangles
  #   min.node.size: filter all leaf nodes that are not larger than specified 
  #     value for faster processing
  
  interact <- strsplit(interact, '_')[[1]]
  if (is.null(varnames.grp)) varnames.grp <- 1:ncol(x)
  interact <- int2Id(interact, varnames.grp, directed=TRUE, split=TRUE)

  print('Extracting paths...')
  out <- getPathsTree(tree.info, nf, interact) 

  # if min.node.size < 1, it is assumed to be given as quantile
  if (min.node.size < 1 & is.factor(y)) { 
    m1 <- quantile(out$size.node[out$prediction == 2], min.node.size)
    m0 <- quantile(out$size.node[out$prediction == 1], min.node.size)
    out <- filter(out, size.node > m1 & prediction == 2 | 
                    size.node > m0 & prediction == 1)
  } else if (min.node.size < 1) {
    m1 <- quantile(out$size.node, min.node.size)
    out <- filter(out, size.node > m)
  } else {
    out <- filter(out, size.node > min.node.size)
  }
  
  if (is.factor(y)) 
    out <- mutate(out, prediction = prediction - 1)
  
  return(out)
}

plotInt2 <- function(rectangles, interact, x, y, 
                     grid.size=100, col.pal=c('blue', 'yellow'), 
                     xlab=NULL, ylab=NULL, zlab=NULL,
                     range.color=NULL,
                     z.range=c(0,1),
                     n.cols=100, grids=NULL, axes=TRUE,
                     varnames.grp=colnames(x),
                     groupFUN=mean,
                     pred.prob=FALSE, min.node.size=10) {
  # Generates surface map of order-2 interaction
  # args:
  #   rectangles: hyprerectangle list as generated by forestHyperrectangle
  #   interact.plot: order-2 interaction to plot
  #   grid.size: number of bins to plot surface map over
  #   col.pal: color palette of surface map
  #   xlab, ylab, zlab: axis labels
  #   range.color: range of color values
  #   z.range: range for response axis
  #   n.cols: number of colors in color pal
  #   grids: user generated grid to plot over. If supplied, grid.size is 
  #     ignored
  #   axes: T/F indicating whether axes should be plotted
  #   varnames.group: character vector indicating feature grouping
  #   groupFUN: function to use for grouping columns of x
  #   pred.prob: T/F indicating whether the z axis should indicate predicted
  #     probability from the forest or raw data distribution
  #   min.node.size: minimum leaf node size to use for grid
  require(rgl)

  interact <- strsplit(interact, '_')[[1]]
  if (is.null(varnames.grp)) varnames.grp <- 1:ncol(x)
  interact <- int2Id(interact, varnames.grp, directed=TRUE, split=TRUE)
  stopifnot(length(interact) == 2) 

  # Group data matrix if grouping features indicated
  if (!is.null(varnames.grp)) {
    stopifnot(length(varnames.grp) == ncol(x))
    x <- sapply(unique(varnames.grp), function(g) {
      apply(as.matrix(x[,varnames.grp == g]), MAR=1, groupFUN)
    })
  }
  
  n <- nrow(x)
  p <- ncol(x)
  if (is.factor(y)) y <- as.numeric(y) - 1
  
  # generate grid to plot surface over either as raw values or quantiles
  intp1 <- interact[1]
  intp2 <- interact[2]
  
  if (is.null(grids)) {
    g1 <- seq(min(x[,intp1]), max(x[,intp1]), length.out=grid.size)
    g2 <- seq(min(x[,intp1]), max(x[,intp2]), length.out=grid.size)
    g1.n <- g1
    g2.n <- g2
  } else {
    g1 <- grids$g1
    g2 <- grids$g2
    grid.size <- length(g1)
    g1.n <- as.numeric(gsub('%', '', names(g1)))
    g2.n <- as.numeric(gsub('%', '', names(g2)))
    
    g1.n <- seq(0, 1, length.out=length(g1))
    g2.n <- seq(0, 1, length.out=length(g2))
  }
  
  # Evaluate responses over grid based on RF hyperrectangles
  grid <- matrix(0, nrow=grid.size, ncol=grid.size)
  gg <- array(0, dim=c(grid.size, grid.size, nrow(rectangles)))
  rectangles <- filter(rectangles, size.node >= min.node.size)
  removed <- rep(FALSE, nrow(rectangles))
  for (i in 1:nrow(rectangles)) {

    rtemp <- rectangles[i,]
    tt1 <- unlist(rtemp$splits)[unlist(rtemp$vars) == intp1]
    tt2 <- unlist(rtemp$splits)[unlist(rtemp$vars) == intp2]
    
    if (intp1 <= p) {
      idcs.1 <- g1 <= tt1
      x1 <- x[, intp1] <= tt1
    } else {
      idcs.1 <- g1 >= tt1
      intp11 <- intp1 %% p + p * (intp1 %% p == 0)
      x1 <- x[,intp11] >= tt1
    }
    
    if (intp2 <= p) {
      idcs.2 <- g2 <= tt2
      x2 <- x[, intp2] <= tt2
    } else {
      idcs.2 <- g2 >= tt2
      intp22 <- intp2 %% p + p * (intp2 %% p == 0)
      x2 <- x[,intp22] >= tt2
    }
  
    if (pred.prob) {
      yy <- rectangles$prediction[i]
      grid[idcs.1, idcs.2] <- grid[idcs.1, idcs.2] + yy * rectangles$size.node[i]
    } else {
      # Evaluate average response in partitioned space
  
      if (!any(x1 & x2)) {
        # Remove regions containing no observations
        removed[i] <- TRUE
        next
      }
      
      grid[idcs.1, idcs.2] <- grid[idcs.1, idcs.2] +  mean(y[x1 & x2]) * rectangles$size.node[i]
      grid[!idcs.1, idcs.2] <- grid[!idcs.1, idcs.2] + mean(y[!x1 | !x2]) * rectangles$size.node[i]
      grid[idcs.1, !idcs.2] <- grid[idcs.1, !idcs.2] + mean(y[!x1 | !x2]) * rectangles$size.node[i]
      grid[!idcs.1, !idcs.2] <- grid[!idcs.1, !idcs.2] + mean(y[!x1 | !x2]) * rectangles$size.node[i]
      
      gg[idcs.1, idcs.2, i] <- ifelse(any(x1 & x2), mean(y[x1 & x2]), 0) * rectangles$size.node[i]
      gg[!idcs.1, idcs.2, i] <- ifelse(any(!x1 & x2), mean(y[!x1 | !x2]), 0) * rectangles$size.node[i]
      gg[idcs.1, !idcs.2, i] <- ifelse(any(x1 & !x2), mean(y[!x1 | !x2]), 0) * rectangles$size.node[i]
      gg[!idcs.1, !idcs.2, i] <- ifelse(any(!x1 & !x2), mean(y[!x1 | !x2]), 0) * rectangles$size.node[i]
      
    }
  }
  
  # rescale surface for node size 
  grid <- (grid / sum(rectangles$size.node[!removed]))
  
  if (is.null(range.color)) range.color <- range(grid)
  palette <- colorRampPalette(col.pal)
  colors <- palette(n.cols)
  facet.col <- cut(c(range.color, as.vector(grid)), n.cols)[-seq(2)]

  persp3d(x=g1.n, y=g2.n, z=grid, 
          xlab=xlab,
          ylab=ylab,
          zlab=zlab, zlim=z.range, 
          col=colors[facet.col],
          axes=axes)
  
  #return(grid)
}

quantileGrid <- function(x, grid.size, interact) {
  stopifnot(length(interact) == 2)
  grid.size <- grid.size + 1
  grids <- list()
  grids$g1 <- quantile(x[,interact[1]], probs=seq(0, 1, length.out=grid.size))
  grids$g2 <- quantile(x[,interact[2]], probs=seq(0, 1, length.out=grid.size))
  return(grids)
}

int2Id <- function(int, varnames.grp, directed=FALSE, split=FALSE) {
  # Determine integer index of named variable in nf matrix (directed or not)
  # args:
  #   int: a character vector of interacting features
  #   varnames.grp: character vector indicating feature grouping
  #   directed: if TRUE, indicated interactions are directed
  #   split: if TRUE, int contains one entry per interacting feature  
  if (!split) int <- strsplit(int, '_')[[1]]
  if (directed) {
    dir <- grep('\\+$', int)  
    varnames.grp <- gsub('[\\+\\-]', '', varnames.grp)
    int <- gsub('[\\+\\-]', '', int)
  }
  
  varnames.grp <- unique(varnames.grp)
  id <- sapply(int, function(i) which(varnames.grp == i))
  if (directed) {
    adjust <- rep(0, length(int))
    adjust[dir] <- length(varnames.grp)
    id <- id + adjust
  }
  
  return(id)
}
